# fly.toml app configuration file generated for divine-money on 2024-06-27T12:11:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divine-money'
primary_region = 'jnb'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '21'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = ""
  worker = "php /var/www/html/artisan queue:listen --queue=high,default --timeout=60 --sleep=3 --tries=3"
#   ws = "php /var/www/html/artisan reverb:start --port=9000 --debug"

# [[services]]
#     internal_port = 9000
#     protocol = 'tcp'
#     processes = ['ws']
#     force_https = true

#     [[services.ports]]
#       handlers = ['tls']
#       port = 9000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
